# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pwabuilder-cloudapk(pre)
on:
  push:
    branches:
      - dev
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login with Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_APP_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to registry
        uses: azure/docker-login@v2
        with:
          login-server: https://pwabuilder.azurecr.io/
          username: ${{
            secrets.AzureAppService_ContainerUsername_c4f6902b5ee546e8847acb25a00561b6
            }}
          password: ${{
            secrets.AzureAppService_lContainerPassword_4fbee4d970264b12bb65c9bad20ba87f
            }}

      - run: |
          docker build . -t pwabuilder.azurecr.io/${{secrets.AzureAppService_ContainerUsername_c4f6902b5ee546e8847acb25a00561b6}}/cloudapk-dev:preview
          docker push pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c4f6902b5ee546e8847acb25a00561b6 }}/cloudapk-dev:preview
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pre
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Login with Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_APP_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: pwabuilder-cloudapk
          slot-name: pre
          images: pwabuilder.azurecr.io/${{secrets.AzureAppService_ContainerUsername_c4f6902b5ee546e8847acb25a00561b6}}/cloudapk-dev:preview
